const express=require('express');
const db=require('../database');
const login=require('../middleware/login');
const {isCommand,isApproved,requireContentManager,requireCommand}=require('../middleware/access');
const router=express.Router();
const KEYS=['comunicados','avisos','documentacao','liberacao-delta'];
function actor(req){if(req.session?.admin)return {tipo:'ADMINISTRADOR',id:req.session.admin.id,nome:req.session.admin.nome||req.session.admin.username};return {tipo:String(req.session.user?.cargo||'USUARIO').toUpperCase(),id:req.session.user?.id,nome:req.session.user?.nome||req.session.user?.username};}
async function log(req,acao,entidade,id,detalhes=''){const a=actor(req);await db.run(`INSERT INTO logs_sistema(usuario_tipo,usuario_id,usuario_nome,acao,entidade,entidade_id,detalhes) VALUES(?,?,?,?,?,?,?)`,[a.tipo,a.id,a.nome,acao,entidade,id||null,detalhes]);}
async function canRead(key,req){return await isCommand(req)||await isApproved(req);}
router.get('/suggestions/mine',login,async (req,res)=>res.json({sugestoes:await db.all(`SELECT * FROM sugestoes WHERE usuario_id=? ORDER BY id DESC`,[req.session.user?.id||0])}));
router.post('/suggestions',login,async (req,res)=>{if(!req.session.user)return res.status(403).json({erro:'Faça login como usuário.'});const texto=String(req.body?.texto||'').trim();if(texto.length<5)return res.status(400).json({erro:'A sugestão precisa ter pelo menos 5 caracteres.'});const r=await db.run('INSERT INTO sugestoes(usuario_id,texto) VALUES(?,?)',[req.session.user.id,texto]);await log(req,'NOVA SUGESTÃO','SUGESTAO',r.lastInsertRowid,texto.slice(0,200));res.status(201).json({sucesso:true,id:Number(r.lastInsertRowid)});});
router.get('/suggestions/all',requireCommand,async (req,res)=>res.json({sugestoes:await db.all(`SELECT s.*,u.nome,u.username FROM sugestoes s JOIN users u ON u.id=s.usuario_id ORDER BY s.id DESC`)}));
router.patch('/suggestions/:id',requireCommand,async (req,res)=>{const id=Number(req.params.id),row=await db.get('SELECT id FROM sugestoes WHERE id=?',[id]);if(!row)return res.status(404).json({erro:'Sugestão não encontrada.'});const status=String(req.body?.status||'NOVA').toUpperCase(),resposta=String(req.body?.resposta||'').trim();if(!['NOVA','EM_ANALISE','RESPONDIDA','ARQUIVADA'].includes(status))return res.status(400).json({erro:'Status inválido.'});await db.run(`UPDATE sugestoes SET status=?,resposta=?,responsavel_id=?,atualizado_em=datetime('now') WHERE id=?`,[status,resposta,req.session.admin?.id||req.session.user?.id||null,id]);await log(req,'ATUALIZAÇÃO DE SUGESTÃO','SUGESTAO',id,`Status: ${status}`);res.json({sucesso:true});});
router.get('/:key',login,async (req,res)=>{const key=String(req.params.key||'').toLowerCase();if(!KEYS.includes(key))return res.status(404).json({erro:'Módulo não encontrado.'});if(!await canRead(key,req))return res.status(403).json({erro:'Você não possui acesso a este módulo.'});res.json({conteudos:await db.all(`SELECT id,chave,titulo,conteudo,ordem,atualizado_em FROM portal_conteudos WHERE chave=? AND ativo=1 ORDER BY ordem,id`,[key])});});
router.post('/:key',requireContentManager,async (req,res)=>{const key=String(req.params.key||'').toLowerCase();if(!KEYS.includes(key))return res.status(404).json({erro:'Módulo não encontrado.'});const titulo=String(req.body?.titulo||'').trim(),conteudo=String(req.body?.conteudo||'').trim(),ordem=Number(req.body?.ordem||0);if(!titulo||!conteudo)return res.status(400).json({erro:'Título e conteúdo são obrigatórios.'});const a=actor(req),r=await db.run(`INSERT INTO portal_conteudos(chave,titulo,conteudo,ordem,criado_por,atualizado_por) VALUES(?,?,?,?,?,?)`,[key,titulo,conteudo,ordem,a.id,a.id]);await log(req,'CRIAÇÃO DE CONTEÚDO','PORTAL_CONTEUDO',r.lastInsertRowid,`${key}: ${titulo}`);res.status(201).json({sucesso:true,id:Number(r.lastInsertRowid)});});
router.patch('/:key/:id',requireContentManager,async (req,res)=>{const key=String(req.params.key||'').toLowerCase(),id=Number(req.params.id);if(!KEYS.includes(key))return res.status(404).json({erro:'Módulo não encontrado.'});const old=await db.get('SELECT * FROM portal_conteudos WHERE id=? AND chave=?',[id,key]);if(!old)return res.status(404).json({erro:'Conteúdo não encontrado.'});const titulo=String(req.body?.titulo??old.titulo).trim(),conteudo=String(req.body?.conteudo??old.conteudo).trim(),ordem=Number(req.body?.ordem??old.ordem);if(!titulo||!conteudo)return res.status(400).json({erro:'Título e conteúdo são obrigatórios.'});const a=actor(req);await db.run(`UPDATE portal_conteudos SET titulo=?,conteudo=?,ordem=?,atualizado_por=?,atualizado_em=datetime('now') WHERE id=?`,[titulo,conteudo,ordem,a.id,id]);await log(req,'ALTERAÇÃO DE CONTEÚDO','PORTAL_CONTEUDO',id,`${key}: ${titulo}`);res.json({sucesso:true});});
router.delete('/:key/:id',requireContentManager,async (req,res)=>{const key=String(req.params.key||'').toLowerCase(),id=Number(req.params.id);if(!KEYS.includes(key))return res.status(404).json({erro:'Módulo não encontrado.'});const old=await db.get('SELECT titulo FROM portal_conteudos WHERE id=? AND chave=?',[id,key]);if(!old)return res.status(404).json({erro:'Conteúdo não encontrado.'});const result=await db.run('DELETE FROM portal_conteudos WHERE id=? AND chave=?',[id,key]);if(Number(result?.changes||0)!==1)return res.status(409).json({erro:'O conteúdo não pôde ser excluído do banco de dados.'});await log(req,'EXCLUSÃO DE CONTEÚDO','PORTAL_CONTEUDO',id,`${key}: ${old.titulo}`);res.json({sucesso:true});});
module.exports=router;
