const express=require('express');
const db=require('../database');
const requireLogin=require('../middleware/login');
const hierarchyAuth=require('../middleware/hierarchy');
const router=express.Router();
function actor(req){if(req.session?.admin)return {tipo:'ADMINISTRADOR',id:Number(req.session.admin.id)||null,nome:req.session.admin.nome||req.session.admin.username};return {tipo:String(req.session.user?.cargo||'PILOTO').toUpperCase(),id:Number(req.session.user?.id)||null,nome:req.session.user?.nome||req.session.user?.username};}
function canViewAll(req){return !!req.session?.admin||hierarchyAuth.isHierarchyManager(req);}
function writeLog(req,acao,id,detalhes){const a=actor(req);db.run(`INSERT INTO logs_sistema (usuario_tipo,usuario_id,usuario_nome,acao,entidade,entidade_id,detalhes) VALUES (?,?,?,?,?,?,?)`,[a.tipo,a.id,a.nome,acao,'RELATORIO_ACAO',id,detalhes||'']);}
function normalize(b){return {nome_acao:String(b.nome_acao||'').trim(),data_acao:String(b.data_acao||'').trim(),veiculo1:String(b.veiculo1||'').trim(),veiculo2:String(b.veiculo2||'').trim(),daec:String(b.daec||'').trim(),resultado:String(b.resultado||'').trim(),bo:String(b.bo||'').trim(),quantidade_refens:Number.isFinite(Number(b.quantidade_refens))?Math.max(0,Math.floor(Number(b.quantidade_refens))):0,qra_negociador:String(b.qra_negociador||'').trim(),observacoes:String(b.observacoes||'').trim()};}
function validate(b){if(!b.nome_acao)return 'Informe o nome da ação.';if(!b.data_acao)return 'Informe a data da ação.';if(!b.resultado)return 'Informe o resultado.';if(!b.bo)return 'Informe o B.O. ou selecione que não houve B.O.';if(!b.daec)return 'Informe o DAEC ou selecione que não houve DAEC.';if(!b.qra_negociador)return 'Informe o negociador ou selecione que não houve negociação.';return null;}
router.get('/',requireLogin,(req,res)=>{try{const all=canViewAll(req),q=String(req.query.q||'').trim(),piloto=String(req.query.piloto||'').trim();let sql=`SELECT r.*,u.nome AS responsavel_nome,u.username AS responsavel_username,u.cargo_delta FROM relatorios_acoes r LEFT JOIN users u ON u.id=r.usuario_id WHERE 1=1`,p=[];if(!all){sql+=` AND r.usuario_id=?`;p.push(req.session.user.id)}if(q){sql+=` AND (r.nome_acao LIKE ? OR r.resultado LIKE ? OR r.bo LIKE ? OR r.qra_negociador LIKE ?)`;const x=`%${q}%`;p.push(x,x,x,x)}if(piloto&&all){sql+=` AND (u.nome LIKE ? OR u.username LIKE ?)`;p.push(`%${piloto}%`,`%${piloto}%`)}sql+=` ORDER BY r.id DESC LIMIT 500`;res.json({relatorios:db.all(sql,p),podeVerTodos:all});}catch(e){console.error(e);res.status(500).json({erro:'Não foi possível carregar os relatórios.'});}});
router.get('/resumo',requireLogin,(req,res)=>{try{const all=canViewAll(req);const where=all?'':'WHERE usuario_id=?',p=all?[]:[req.session.user.id];const total=db.get(`SELECT COUNT(*) total FROM relatorios_acoes ${where}`,p)?.total||0;const mes=db.get(`SELECT COUNT(*) total FROM relatorios_acoes ${where}${where?' AND':'WHERE'} strftime('%Y-%m',data_acao)=strftime('%Y-%m','now')`,p)?.total||0;const ref=db.get(`SELECT COALESCE(SUM(quantidade_refens),0) total FROM relatorios_acoes ${where}`,p)?.total||0;res.json({total:Number(total),mes:Number(mes),refens:Number(ref)});}catch(e){console.error(e);res.status(500).json({erro:'Não foi possível carregar o resumo.'});}});
router.get('/:id',requireLogin,(req,res)=>{try{const id=Number(req.params.id),r=db.get(`SELECT r.*,u.nome AS responsavel_nome,u.username AS responsavel_username,u.cargo_delta FROM relatorios_acoes r LEFT JOIN users u ON u.id=r.usuario_id WHERE r.id=?`,[id]);if(!r)return res.status(404).json({erro:'Relatório não encontrado.'});if(!canViewAll(req)&&Number(r.usuario_id)!==Number(req.session.user.id))return res.status(403).json({erro:'Você só pode visualizar seus próprios relatórios.'});res.json({relatorio:r});}catch(e){console.error(e);res.status(500).json({erro:'Não foi possível carregar o relatório.'});}});
router.post('/',requireLogin,(req,res)=>{try{if(!req.session.user)return res.status(403).json({erro:'Faça login com uma conta de piloto/comando.'});const b=normalize(req.body||{}),err=validate(b);if(err)return res.status(400).json({erro:err});const r=db.run(`INSERT INTO relatorios_acoes (usuario_id,nome_acao,data_acao,veiculo1,veiculo2,daec,resultado,bo,quantidade_refens,qra_negociador,observacoes) VALUES (?,?,?,?,?,?,?,?,?,?,?)`,[req.session.user.id,b.nome_acao,b.data_acao,b.veiculo1,b.veiculo2,b.daec,b.resultado,b.bo,b.quantidade_refens,b.qra_negociador,b.observacoes]);const id=Number(r.lastInsertRowid); const a=actor(req); db.run(`INSERT INTO relatorios_acoes_historico (relatorio_id,usuario_tipo,usuario_id,acao,dados) VALUES (?,?,?,?,?)`,[id,a.tipo,a.id,'CRIAÇÃO',JSON.stringify(b)]); writeLog(req,'CRIAÇÃO DE RELATÓRIO',''+id,`Ação: ${b.nome_acao}`);res.status(201).json({sucesso:true,id,mensagem:'Relatório de ação fechado registrado.'});}catch(e){console.error(e);res.status(500).json({erro:'Não foi possível salvar o relatório.'});}});
router.patch('/:id',requireLogin,(req,res)=>{try{const id=Number(req.params.id),old=db.get(`SELECT * FROM relatorios_acoes WHERE id=?`,[id]);if(!old)return res.status(404).json({erro:'Relatório não encontrado.'});if(!canViewAll(req)&&Number(old.usuario_id)!==Number(req.session.user.id))return res.status(403).json({erro:'Sem permissão para editar este relatório.'});const b=normalize(req.body||{}),err=validate(b);if(err)return res.status(400).json({erro:err});db.run(`UPDATE relatorios_acoes SET nome_acao=?,data_acao=?,veiculo1=?,veiculo2=?,daec=?,resultado=?,bo=?,quantidade_refens=?,qra_negociador=?,observacoes=?,atualizado_em=datetime('now') WHERE id=?`,[b.nome_acao,b.data_acao,b.veiculo1,b.veiculo2,b.daec,b.resultado,b.bo,b.quantidade_refens,b.qra_negociador,b.observacoes,id]); const a=actor(req); db.run(`INSERT INTO relatorios_acoes_historico (relatorio_id,usuario_tipo,usuario_id,acao,dados) VALUES (?,?,?,?,?)`,[id,a.tipo,a.id,'ALTERAÇÃO',JSON.stringify(b)]);writeLog(req,'ALTERAÇÃO DE RELATÓRIO',id,`Ação: ${b.nome_acao}`);res.json({sucesso:true,mensagem:'Relatório atualizado.'});}catch(e){console.error(e);res.status(500).json({erro:'Não foi possível atualizar o relatório.'});}});
router.delete('/:id',hierarchyAuth,(req,res)=>{try{const id=Number(req.params.id),r=db.get(`SELECT * FROM relatorios_acoes WHERE id=?`,[id]);if(!r)return res.status(404).json({erro:'Relatório não encontrado.'});const a=actor(req); db.run(`INSERT INTO relatorios_acoes_historico (relatorio_id,usuario_tipo,usuario_id,acao,dados) VALUES (?,?,?,?,?)`,[id,a.tipo,a.id,'EXCLUSÃO',JSON.stringify({nome_acao:r.nome_acao})]); const result=db.run(`DELETE FROM relatorios_acoes WHERE id=?`,[id]);if(Number(result?.changes||0)!==1)return res.status(409).json({erro:'O relatório não pôde ser excluído do banco de dados.'});writeLog(req,'EXCLUSÃO DE RELATÓRIO',id,`Ação: ${r.nome_acao}`);res.json({sucesso:true,mensagem:'Relatório excluído.'});}catch(e){console.error(e);res.status(500).json({erro:'Não foi possível excluir o relatório.'});}});
module.exports=router;
